version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./acmeData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= AcmeDB
    ports:
      - 27017:27017

  licenseinit:
    build: ./licenseinit
    links:
      - db

  assetinit:
    build: ./assetinit
    links:
      - db
  
  backend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      target: base
    volumes:
      - ./src:/home/acmeApp
      - ./nodemon.json:/home/acmeApp/nodemon.json
    container_name: backend
    expose:
      - '4000'
    ports:
      - '4001:4000'
    command: npm run dev